name: Angular CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular production
        run: npm run build -- --configuration=production

      - name: Verify build files
        run: |
          echo "Estructura de carpetas en dist/:"
          ls -R dist/
          if [ ! -f "dist/front-movie-app/browser/index.html" ]; then
            echo "❌ Error: El archivo index.html no se encontró en dist/front-movie-app/browser/"
            echo "Posible solución: Revisa angular.json y ajusta el outputPath o el builder"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/front-movie-app/browser 
          keep_files: false
          enable_jekyll: false
